[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font Mono", style = "regular" }

[scrolling]
multiplier = 0

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
